Iteam1337/Iteam-next-site

src/sections/about/Team.js
src/sections/about/team.json

https://trello.com/c/ghWr4U84/48-se-%C3%B6ver-listan-och-l%C3%A4gg-in-telefonnr

chore: Bring coworker list up to date, add phone numbers

---

src/sections/startpage/Faq.js
src/utils/globalStyle.js

https://trello.com/c/D2LXrqgX/17-jonna-fyller-i-mer-text-ang%C3%A5ende-priss%C3%A4ttning-information

chore: faq text

---

src/sections/startpage/Feature.js

fix: new copy

---

src/components/HubspotForm/index.js
src/sections/iteamX/Contact.js
src/sections/mvp/CTA.js

https://trello.com/c/P4Yswlox/26-in-med-hubspot-formul%C3%A4r
https://trello.com/c/OMjcd6h6/37-l%C3%A4gg-in-formul%C3%A4r-fr%C3%A5n-hubspot
Add form for hubspot.

Feat: hubspot form

---

package-lock.json
package.json
src/context/GlobalContext.js
yarn.lock

feat: add hubspot chat

---

src/pages/case/skatteverket.js
src/pages/case/tjejjouren-vast.js
src/sections/case/CaseList1.js
src/sections/case/skatteverket/index.js
src/sections/case/tjejjouren-vast/CaseDetails.js

add content for tjejjouren and skatteverket

Chore: content

---

src/sections/career/Roles.js

Feedback from https://trello.com/c/uapmHl6F/43-l%C3%A4gg-upp-lediga-tj%C3%A4nster

chore: Adjust job opening card visuals

---

src/components/HubspotForm/index.js
src/sections/iteamX/CaseStudies.js
src/sections/iteamX/Content.js
src/sections/iteamX/Content2.js
src/sections/mvp/Feature2.js
src/sections/scaleup/AgileCoach.js
src/sections/scaleup/Tech.js
src/sections/scaleup/UX.js
src/sections/startpage/Hero.js

Same size on the case cards. 
Also fixed some errors from the console.

chore: case card iteam x

---

src/components/Core/Anchor.js
src/components/Core/index.js
src/components/Footer/Footer.js
src/components/PostCard/PostCard.js
src/pages/aktuellt/[id].js
src/pages/book.js
src/pages/karriar/backend-developer.js
src/pages/karriar/head-of-development.js
src/sections/about/CTA.js
src/sections/aktuellt/PostDetails.js
src/sections/case/CTA.js
src/sections/case/matcha-kontraktet/CaseDetails.js
src/sections/case/trr/CaseDetails.js
src/sections/karriar/Content.js
src/sections/karriar/Roles.js
src/sections/mvp/Content1.js
src/sections/mvp/Feature1.js
src/sections/scaleup/Content1.js
src/sections/scaleup/Content2.js
src/sections/startpage/CTA.js
src/sections/startpage/Pricing.js
src/utils/theme.js

Update link colors
Black background -> green links 
White background -> blue links

Chore: link colors

---

client/src/sanity-client.js
client/src/sections/about/CoworkerHero.js
client/src/sections/about/Team.js
studio/README.md
studio/sanity.json

When you run the project local we now use a different dataset so that changes won't effect on the deployed studio.

chore: dataset

---

client/src/components/BlockContent/index.js
client/src/pages/case/[slug].js

Where suppose to fix a internal link problem, that turned out being in the CMS. 
This pr include handling `_blank` for links in block test instead.

fix: internal link

---

client/src/pages/about/index.js
client/src/pages/aktuellt/index.js
client/src/pages/case/index.js
studio/resolveProductionUrl.js
studio/src/deskStructure.js

live preview added for landingpages
- case 
- news 
- about

chore: live preview

---

client/src/components/CaseCard/CaseCard.js
client/src/components/Header/Header.js
client/src/components/PostCard/PostCard.js
client/src/pages/aktuellt/[slug].js
client/src/sections/karriar/Feature.js
client/src/sections/startpage/GlitchHero.js

fix some errors we had in the console locally

fix: console errors

---

client/src/components/BlockContent/index.js
client/src/components/Sections/SectionWithButtonAndTextGrid.js
client/src/components/Typography/index.js
client/src/sections/startpage/Faq.js

fix: add prop to change link color

---

client/src/pages/about/index.js
client/src/pages/aktuellt/[slug].js
client/src/pages/aktuellt/index.js
client/src/pages/book.js
client/src/pages/case/[slug].js
client/src/pages/case/index.js
client/src/pages/iteamX.js
client/src/pages/karriar/[slug].js
client/src/pages/karriar/index.js
client/src/pages/mvp.js
client/src/pages/scaleup.js

Ska alla sidor verkligen ha `%s | Aktuellt på Iteam`?

fix: typo correction

---

client/src/components/Carousel/Carousel.js

fix: add check if email exists email

---

client/src/pages/about/index.js
client/src/sections/about/CoworkerHero.js
client/src/sections/about/Medarbetare.js
client/src/sections/about/SocialMediaLinks.js
client/src/sections/about/Team.js
client/yarn.lock

Adds social media links on teams page (Om oss) and extract it as a separate component.

SocialMediaLinks component for reuse

---

client/src/components/Carousel/Carousel.js
client/src/pages/index.js
client/src/utils/helpers.js
studio/schemas/modules/carousel.js

Also add 'Läs mer..' if case if referenced

feat: add reference in carousel and link to case

---

client/src/pages/mvp.js
client/src/pages/scaleup.js

fix: 404-links in offer page carousel by completing graphql query

---

client/src/components/Card/BaseCard.js

The card link was not working everywhere on the card and now it is.

fix: make link work on whole card

---

client/src/components/Footer/Footer.js
studio/schemas/modules/footer.js

Adds new fields in Sanity and applies the data in frontend.

refactor: footer address

---

client/package-lock.json
client/package.json
client/src/pages/_app.js
client/src/pages/index.js

Adds PostHog to the site for more granular analytics.

chore: add posthog
